DROP TABLE IF EXISTS length_type;

-- DROP SEQUENCE IF EXISTS length_type_seq;
-- CREATE SEQUENCE length_type_seq;

CREATE TABLE length_type (
  "length_type_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "value" decimal(15,8) NOT NULL
  -- PRIMARY KEY("length_type_id")
);

SELECT setval('length_type_length_type_id_seq', 4, true); -- last inserted id by sample data
