DROP TABLE IF EXISTS manufacturer;

-- DROP SEQUENCE IF EXISTS manufacturer_seq;
-- CREATE SEQUENCE manufacturer_seq;

CREATE TABLE manufacturer (
  "manufacturer_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "name" varchar(191) NOT NULL DEFAULT '',
  "slug" varchar(191) NOT NULL DEFAULT '',
  "image" varchar(191) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0
  -- PRIMARY KEY("manufacturer_id")
);

SELECT setval('manufacturer_manufacturer_id_seq', 6, true); -- last inserted id by sample data