DROP TABLE IF EXISTS stock_status;

-- DROP SEQUENCE IF EXISTS stock_status_stock_status_id_seq;
-- CREATE SEQUENCE stock_status_stock_status_id_seq;


CREATE TABLE stock_status (
  "stock_status_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL,
  "name" varchar(32) NOT NULL
  -- PRIMARY KEY("stock_status_id","language_id")
);

SELECT setval('stock_status_stock_status_id_seq', 7, true); -- last inserted id by sample data