DROP TABLE IF EXISTS weight_type;

-- DROP SEQUENCE IF EXISTS weight_type_weight_type_id_seq;
-- CREATE SEQUENCE weight_type_weight_type_id_seq;


CREATE TABLE weight_type (
  "weight_type_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "value" decimal(15,8) NOT NULL DEFAULT 0.00000000
  -- PRIMARY KEY("weight_type_id")
);

SELECT setval('weight_type_weight_type_id_seq', 5, true); -- last inserted id by sample data