-- DROP TABLE IF EXISTS "newsletter_list";

CREATE TABLE IF NOT EXISTS newsletter_list (
  "newsletter_list_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "name" varchar(254) NOT NULL,
  "data" text NOT NULL DEFAULT '',
  "status"tinyint(6) NOT NULL DEFAULT '0',
  "created_at" timestamp(0) NOT NULL DEFAULT now(),
  "updated_at" timestamp(0) NOT NULL DEFAULT now()
);
			