DROP TABLE IF EXISTS attribute_group;

-- DROP SEQUENCE IF EXISTS attribute_group_attribute_group_id_seq;
-- CREATE SEQUENCE attribute_group_attribute_group_id_seq;

CREATE TABLE "attribute_group" (
 "attribute_group_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
 "sort_order" INT NOT NULL DEFAULT 0
 -- PRIMARY KEY("attribute_group_id")
);

SELECT setval('attribute_group_attribute_group_id_seq', 4, true); -- last inserted id by sample data
