DROP TABLE IF EXISTS "order";

DROP SEQUENCE IF EXISTS order_seq;
CREATE SEQUENCE order_seq;


CREATE TABLE "order" (
  "order_id" int check ("order_id" > 0) NOT NULL DEFAULT NEXTVAL ('order_seq'),
  "invoice_no" int check ("invoice_no" > 0) NOT NULL DEFAULT 0,
  "invoice_prefix" varchar(26) NOT NULL DEFAULT 'INV-',
  "site_id" smallint NOT NULL DEFAULT 0,
  "site_name" varchar(64) NOT NULL,
  "site_url" varchar(191) NOT NULL,
  "user_id" int check ("user_id" > 0) NOT NULL DEFAULT 0,
  "user_group_id" int check ("user_group_id" > 0) NOT NULL DEFAULT 0,
  "first_name" varchar(32) NOT NULL,
  "last_name" varchar(32) NOT NULL,
  "email" varchar(96) NOT NULL,
  "phone_number" varchar(32) NOT NULL,
  "billing_first_name" varchar(32) NOT NULL,
  "billing_last_name" varchar(32) NOT NULL,
  "billing_company" varchar(60) NOT NULL,
  "billing_address_1" varchar(128) NOT NULL,
  "billing_address_2" varchar(128) NOT NULL,
  "billing_city" varchar(128) NOT NULL,
  "billing_post_code" varchar(10) NOT NULL,
  "billing_country" varchar(128) NOT NULL,
  "billing_country_id" int check ("billing_country_id" > 0) NOT NULL,
--  "billing_region" varchar(128) NOT NULL,
  "billing_region_id" int check ("billing_region_id" > 0) NOT NULL,
  "billing_address_format" text NOT NULL,
  "billing_fields" text NOT NULL,
  "payment_method" varchar(128) NOT NULL,
  "payment_data" text NOT NULL,
  "shipping_first_name" varchar(32) NOT NULL,
  "shipping_last_name" varchar(32) NOT NULL,
  "shipping_company" varchar(60) NOT NULL,
  "shipping_address_1" varchar(128) NOT NULL,
  "shipping_address_2" varchar(128) NOT NULL,
  "shipping_city" varchar(128) NOT NULL,
  "shipping_post_code" varchar(10) NOT NULL,
  "shipping_country" varchar(128) NOT NULL,
  "shipping_country_id" int check ("shipping_country_id" > 0) NOT NULL,
  "shipping_region" varchar(128) NOT NULL,
  "shipping_region_id" int check ("shipping_region_id" > 0) NOT NULL,
  "shipping_address_format" text NOT NULL,
  "shipping_fields" text NOT NULL,
  "shipping_method" varchar(128) NOT NULL,
  "shipping_data" text NOT NULL,
  "total" decimal(15,4) NOT NULL DEFAULT 0.0000,
  "order_status_id" int check ("order_status_id" > 0) NOT NULL DEFAULT 0,
  "language_id" int check ("language_id" > 0) NOT NULL,
  "currency_id" int check ("currency_id" > 0) NOT NULL,
  "currency_code" varchar(3) NOT NULL,
  "currency_value" decimal(15,8) NOT NULL DEFAULT 1.00000000,
  "notes" text NOT NULL,
  "remote_ip" varchar(40) NOT NULL,
  "forwarded_for_ip" varchar(40) NOT NULL,
  "user_agent" varchar(191) NOT NULL,
  "accept_language" varchar(191) NOT NULL,
  "created_at" timestamp(0) NOT NULL,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("order_id")
);
