DROP TABLE IF EXISTS order_status;

-- DROP SEQUENCE IF EXISTS order_status_order_status_id_seq;
-- CREATE SEQUENCE order_status_order_status_id_seq;


CREATE TABLE order_status (
  "order_status_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL,
  "name" varchar(32) NOT NULL
  -- PRIMARY KEY("order_status_id","language_id")
);

SELECT setval('order_status_order_status_id_seq', 20, true); -- last inserted id by sample data