DROP TABLE IF EXISTS payment_status;

-- DROP SEQUENCE IF EXISTS payment_status_payment_status_id_seq;
-- CREATE SEQUENCE payment_status_payment_status_id_seq;


CREATE TABLE payment_status (
  "payment_status_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL,
  "name" varchar(32) NOT NULL
  -- PRIMARY KEY("payment_status_id","language_id")
);

SELECT setval('payment_status_payment_status_id_seq', 20, true); -- last inserted id by sample data