DROP TABLE IF EXISTS return_resolution;

-- DROP SEQUENCE IF EXISTS return_resolution_return_resolution_id_seq;
-- CREATE SEQUENCE return_resolution_return_resolution_id_seq;


CREATE TABLE return_resolution (
  "return_resolution_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL DEFAULT 0,
  "name" varchar(64) NOT NULL
  -- PRIMARY KEY("return_resolution_id","language_id")
);

SELECT setval('return_resolution_return_resolution_id_seq', 4, true); -- last inserted id by sample data