DROP TABLE IF EXISTS return_status;

-- DROP SEQUENCE IF EXISTS return_status_return_status_id_seq;
-- CREATE SEQUENCE return_status_return_status_id_seq;


CREATE TABLE return_status (
  "return_status_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL DEFAULT 0,
  "name" varchar(32) NOT NULL
  -- PRIMARY KEY("return_status_id","language_id")
);

SELECT setval('return_status_return_status_id_seq', 5, true); -- last inserted id by sample data