DROP TABLE IF EXISTS return_reason;

-- DROP SEQUENCE IF EXISTS return_reason_return_reason_id_seq;
-- CREATE SEQUENCE return_reason_return_reason_id_seq;


CREATE TABLE return_reason (
  "return_reason_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL DEFAULT 0,
  "name" varchar(128) NOT NULL
  -- PRIMARY KEY("return_reason_id","language_id")
);

SELECT setval('return_reason_return_reason_id_seq', 11, true); -- last inserted id by sample data