DROP TABLE IF EXISTS shipping_status;

-- DROP SEQUENCE IF EXISTS shipping_status_shipping_status_id_seq;
-- CREATE SEQUENCE shipping_status_shipping_status_id_seq;


CREATE TABLE shipping_status (
  "shipping_status_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "language_id" int check ("language_id" > 0) NOT NULL,
  "name" varchar(32) NOT NULL
  -- PRIMARY KEY("shipping_status_id","language_id")
);

SELECT setval('shipping_status_shipping_status_id_seq', 20, true); -- last inserted id by sample data