DROP TABLE IF EXISTS option_value;

-- DROP SEQUENCE IF EXISTS option_value_option_value_id_seq;
-- CREATE SEQUENCE option_value_option_value_id_seq;


CREATE TABLE "option_value" (
  "option_value_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "option_id" INT NOT NULL,
  "image" TEXT NOT NULL,
  "sort_order" INT NOT NULL DEFAULT 0
 -- PRIMARY KEY("option_value_id")
);

SELECT setval('option_value_option_value_id_seq', 18, true); -- last inserted id by sample data