INSERT INTO `taxonomy_item_content` VALUES 
(1,1,'Electronics','electronics','Electronics','Electronics','',''),
(2,1,'Fashion','fashion','Fashion','Fashion','',''),
(3,1,'Toys','toys','Toys','Toys','',''),
(4,1,'Books','books','Books','Books','',''),
(5,1,'Computers','computers','Computers','Computers','',''),
(6,1,'Home and Kitchen','home-kitchen','Home and Kitchen','Home and Kitchen','',''),
(7,1,'Games','games','Games','Games','',''),
(8,1,'Smartphones','smartphones','Smartphones','Smartphones','',''),
(9,1,'Software','software','Software','Software','',''),
(10,1,'Appliances','appliances','Appliances','Appliances','',''),
(11,1,'Tablets','tablets','Tablets','Tablets','',''),

(12,1,'Desktops','desktops','Example of taxonomy_item description text','Desktops','Example of taxonomy_item description',''),

(13,1,'category 1','category-1','category 1','category 1','',''),
(14,1,'category 2','category-2','category 2','category 2','',''),
(15,1,'category 5','category-5','category 5','category 5','',''),
(16,1,'category 4','category-4','category 4','category 4','',''),
(17,1,'category 6','category-6','category 6','category 6','',''),
(18,1,'category 7','category-7','category 7','category 7','',''),
(19,1,'category 8','category-8','category 8','category 8','',''),
(20,1,'category 9','category-9','category 9','category 9','',''),
(21,1,'category 11','category-11','category 11','category 11','',''),

(22,1,'MP3 Players','mp3-players','Example of taxonomy_item description text','MP3 Players','',''),


(23,1,'Laptops & Notebooks','laptop-notebooks','Example of taxonomy_item description text','Laptops & Notebooks','',''),
(24,1,'category 12','category-12','category 12','category 12','',''),
(25,1,'Windows','windows','Windows','Windows','',''),
(26,1,'Games','games','Games','Gamess','',''),
(27,1,'category 15','category-15','category 15','category 15','',''),
(28,1,'category 16','category-16','category 16','category 16','',''),
(29,1,'category 17','category-17','category 17','category 17','',''),
(30,1,'category 18','category-18','category 18','category 18','',''),
(31,1,'category 19','category-19','category 19','category 19','',''),
(32,1,'category 20','category-20','category 20','category 20','',''),
(33,1,'category 21','category-21','category 21','category 21','',''),
(34,1,'category 22','category-22','category 22','category 22','',''),
(35,1,'category 23','category-23','category 23','category 23','',''),
(36,1,'category 24','category-24','category 24','category 24','',''),
(37,1,'Tablets','tablets','Tablets','Tablets','',''),
(38,1,'category 25','category-25','category 25','category 25','',''),


(1,2, 'Electronice', 'electronice', 'Electronice', 'Electronice', '', ''),
(2,2, 'Moda', 'moda', 'Moda', 'Moda', '', ''),
(3,2, 'Jucarii', 'jucarii', 'Jucarii', 'Jucarii', '',''),
(4,2, 'Scannere', 'scanere', 'Scanere', 'Scanere', '', ''),
(5,2, 'Carti', 'carti', 'Carti', 'Carti', '', ''),
(6,2, 'Casa si Bucatarie', 'casa-bucatarie', 'Casa si Bucatarie', 'Casa si Bucatarie', '', ''),
(7,2, 'Jocuri', 'jocuri', 'Jocuri', 'Jocuri', '', ''),
(8,2, 'Smartphones', 'smartphones', 'Smartphones', 'Smartphones', '', ''),
(9,2, 'Software', 'software', 'Software', 'Software', '', ''),
(10,2, 'Componente', 'componente', 'Componente', 'Componente', '', ''),
(11,2, 'Tablete', 'tablete', 'Tablete', 'Tablete', '', ''),

(12,2, 'Desktop-uri', 'desktop-uri', 'Exemplu de descriere a categoriei text', 'Desktop', 'Exemplu a descrierii categoriei ',' '),

(13,2, 'category 1', 'category-1', 'category 1', 'category 1', '', ''),
(14,2, 'category 2', 'category-2', 'category 2', 'category 2', '', ''),
(15,2, 'category 5', 'category-5', 'category 5', 'category 5', '', ''),
(16,2, 'category 4', 'category-4', 'category 4', 'category 4', '', ''),
(17,2, 'category 6', 'category-6', 'category 6', 'category 6', '', ''),
(18,2, 'category 7', 'category-7', 'category 7', 'category 7', '', ''),
(19,2, 'category 8', 'category-8', 'category 8', 'category 8', '', ''),
(20,2, 'category 9', 'category-9', 'category 9', 'category 9', '', ''),
(21,2, 'category 11', 'category-11', 'category 11', 'category 11', '', ''),

(22,2, 'Playere MP3', 'playere-mp3', 'Example of taxonomy_item description text',' Playere MP3 ',' ',' ') ,


(23,2, 'Laptopuri si notebook-uri', 'laptop-notebook-uri', 'Example of taxonomy description text ',' Laptopuri si notebook-uri ',' ',' '),
(24,2, 'category 12', 'category-12', 'category 12', 'category 12', '', ''),
(25,2, 'Windows', 'windows', 'Windows', 'Windows', '', ''),
(26,2, 'Jocuro', 'jocuri', 'Jocuri', 'Jocuri', '', ''),
(27,2, 'category 15', 'category-15', 'category 15', 'category 15', '', ''),
(28,2, 'category 16', 'category-16', 'category 16', 'category 16', '', ''),
(29,2, 'category 17', 'category-17', 'category 17', 'category 17', '', ''),
(30,2, 'category 18', 'category-18', 'category 18', 'category 18', '', ''),
(31,2, 'category 19', 'category-19', 'category 19', 'category 19', '', ''),
(32,2, 'category 20', 'category-20', 'category 20', 'category 20', '', ''),
(33,2, 'category 21', 'category-21', 'category 21', 'category 21', '', ''),
(34,2, 'category 22', 'category-22', 'category 22', 'category 22', '', ''),
(35,2, 'category 23', 'category-23', 'category 23', 'category 23', '', ''),
(36,2, 'category 24', 'category-24', 'category 24', 'category 24', '', ''),
(37,2, 'Tablete', 'tablete', 'Tablete', 'Tablete', '', ''),
(38,2, 'category 25', 'test 25', 'test 25', 'test 25', '', ''),
-- tags
(39,1, 'Tag 1', 'tag-1', 'tag 1', 'tag1', '', ''),
(40,1, 'Tag 2', 'tag-2', 'tag 2', 'tag2', '', ''),
(41,1, 'Tag 3', 'tag-3', 'tag 3', 'tag3', '', ''),
-- menu
(42,1, 'Themes', 'themes', 'Themes', 'themes', '', ''),
(43,1, 'Plugins', 'plugins', 'Plugins', 'tag3', '', ''),
(44,1, 'Resources', 'resources', 'Resources', 'tag3', '', ''),
(45,1, 'Github', 'github', 'Github', 'tag3', '', ''),
(46,1, 'Contact', 'Tag 3', 'tag 3', 'tag3', '', ''),
(47,1, 'User documentation', 'Tag 3', 'tag 3', 'tag3', '', ''),
(48,1, 'Developer', 'Developer', 'Developer', 'Developer', '', ''),
(49,1, 'Blog', 'Blog', 'Blog', 'Blog', '', ''),
-- product categories
(50	,1,'Electronics','electronics','Electronics','Electronics','',''),
(51	,1,'Fashion','fashion','Fashion','Fashion','',''),
(52	,1,'Toys','toys','Toys','Toys','',''),
(53	,1,'Books','books','Books','Books','',''),
(54	,1,'Computers','computers','Computers','Computers','',''),
(55	,1,'Home and Kitchen','home-kitchen','Home and Kitchen','Home and Kitchen','',''),
(56	,1,'Games','games','Games','Games','',''),
(57	,1,'Smartphones','smartphones','Smartphones','Smartphones','',''),
(58	,1,'Software','software','Software','Software','',''),
(59	,1,'Appliances','appliances','Appliances','Appliances','',''),
(60	,1,'Tablets','tablets','Tablets','Tablets','',''),
(61	,1,'Desktops','desktops','Example of taxonomy_item description text','Desktops','Example of taxonomy_item description',''),
(62	,1,'category 1','category-1','category 1','category 1','',''),
(63	,1,'category 2','category-2','category 2','category 2','',''),
(64	,1,'category 5','category-5','category 5','category 5','',''),
(65	,1,'category 4','category-4','category 4','category 4','',''),
(66	,1,'category 6','category-6','category 6','category 6','',''),
(67	,1,'category 7','category-7','category 7','category 7','',''),
(68	,1,'category 8','category-8','category 8','category 8','',''),
(69	,1,'category 9','category-9','category 9','category 9','',''),
(70	,1,'category 11','category-11','category 11','category 11','',''),
(71	,1,'MP3 Players','mp3-players','Example of taxonomy_item description text','MP3 Players','',''),
(72	,1,'Laptops & Notebooks','laptop-notebooks','Example of taxonomy_item description text','Laptops & Notebooks','',''),
(73	,1,'category 12','category-12','category 12','category 12','',''),
(74	,1,'Windows','windows','Windows','Windows','',''),
(75	,1,'Games','games','Games','Gamess','',''),
(76	,1,'category 15','category-15','category 15','category 15','',''),
(77	,1,'category 16','category-16','category 16','category 16','',''),
(78	,1,'category 17','category-17','category 17','category 17','',''),
(79	,1,'category 18','category-18','category 18','category 18','',''),
(80	,1,'category 19','category-19','category 19','category 19','',''),
(81	,1,'category 20','category-20','category 20','category 20','',''),
(82	,1,'category 21','category-21','category 21','category 21','',''),
(83	,1,'category 22','category-22','category 22','category 22','',''),
(84	,1,'category 23','category-23','category 23','category 23','',''),
(85	,1,'category 24','category-24','category 24','category 24','',''),
(86	,1,'Tablets','tablets','Tablets','Tablets','',''),
(87	,1,'category 25','category-25','category 25','category 25','',''),

(50	,2, 'Electronice', 'electronice', 'Electronice', 'Electronice', '', ''),
(51	,2, 'Moda', 'moda', 'Moda', 'Moda', '', ''),
(52	,2, 'Jucarii', 'jucarii', 'Jucarii', 'Jucarii', '',''),
(53	,2, 'Scannere', 'scanere', 'Scanere', 'Scanere', '', ''),
(54	,2, 'Carti', 'carti', 'Carti', 'Carti', '', ''),
(55	,2, 'Casa si Bucatarie', 'casa-bucatarie', 'Casa si Bucatarie', 'Casa si Bucatarie', '', ''),
(56	,2, 'Jocuri', 'jocuri', 'Jocuri', 'Jocuri', '', ''),
(57	,2, 'Smartphones', 'smartphones', 'Smartphones', 'Smartphones', '', ''),
(58	,2, 'Software', 'software', 'Software', 'Software', '', ''),
(59	,2, 'Componente', 'componente', 'Componente', 'Componente', '', ''),
(60	,2, 'Tablete', 'tablete', 'Tablete', 'Tablete', '', ''),
(61	,2, 'Desktop-uri', 'desktop-uri', 'Exemplu de descriere a categoriei text', 'Desktop', 'Exemplu a descrierii categoriei ',' '),
(62	,2, 'category 1', 'category-1', 'category 1', 'category 1', '', ''),
(63	,2, 'category 2', 'category-2', 'category 2', 'category 2', '', ''),
(64	,2, 'category 5', 'category-5', 'category 5', 'category 5', '', ''),
(65	,2, 'category 4', 'category-4', 'category 4', 'category 4', '', ''),
(66	,2, 'category 6', 'category-6', 'category 6', 'category 6', '', ''),
(67	,2, 'category 7', 'category-7', 'category 7', 'category 7', '', ''),
(68	,2, 'category 8', 'category-8', 'category 8', 'category 8', '', ''),
(69	,2, 'category 9', 'category-9', 'category 9', 'category 9', '', ''),
(70	,2, 'category 11', 'category-11', 'category 11', 'category 11', '', ''),
(71	,2, 'Playere MP3', 'playere-mp3', 'Example of taxonomy_item description text',' Playere MP3 ',' ',' ') ,
(72	,2, 'Laptopuri si notebook-uri', 'laptop-notebook-uri', 'Example of taxonomy description text ',' Laptopuri si notebook-uri ',' ',' '),
(73	,2, 'category 12', 'category-12', 'category 12', 'category 12', '', ''),
(74	,2, 'Windows', 'windows', 'Windows', 'Windows', '', ''),
(75	,2, 'Jocuro', 'jocuri', 'Jocuri', 'Jocuri', '', ''),
(76	,2, 'category 15', 'category-15', 'category 15', 'category 15', '', ''),
(77	,2, 'category 16', 'category-16', 'category 16', 'category 16', '', ''),
(78	,2, 'category 17', 'category-17', 'category 17', 'category 17', '', ''),
(79	,2, 'category 18', 'category-18', 'category 18', 'category 18', '', ''),
(80	,2, 'category 19', 'category-19', 'category 19', 'category 19', '', ''),
(81	,2, 'category 20', 'category-20', 'category 20', 'category 20', '', ''),
(82	,2, 'category 21', 'category-21', 'category 21', 'category 21', '', ''),
(83	,2, 'category 22', 'category-22', 'category 22', 'category 22', '', ''),
(84	,2, 'category 23', 'category-23', 'category 23', 'category 23', '', ''),
(85	,2, 'category 24', 'category-24', 'category 24', 'category 24', '', ''),
(86	,2, 'Tablete', 'tablete', 'Tablete', 'Tablete', '', ''),
(87	,2, 'category 25', 'test 25', 'test 25', 'test 25', '', '');

