DROP TABLE IF EXISTS region_group;

-- DROP SEQUENCE IF EXISTS region_group_region_group_id_seq;
-- CREATE SEQUENCE region_group_region_group_id_seq;


CREATE TABLE region_group (
  "region_group_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "name" varchar(32) NOT NULL,
  "content" varchar(191) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT now()
  -- PRIMARY KEY("region_group_id")
);

SELECT setval('region_group_region_group_id_seq', 2, true); -- last inserted id by sample data