import(components/posts.tpl)
import(components/products.tpl)
import(components/product.tpl)
import(components/orders.tpl)
import(components/users.tpl)
import(components/languages.tpl)
import(components/admin.tpl)
import(components/comments.tpl)
import(components/news.tpl)
import(components/product/reviews.tpl)
import(components/stats.tpl)
import(components/states.tpl)
import(components/sites.tpl)
import(components/site.tpl)
import(components/order.tpl)
import(components/user/address.tpl)
import(components/pagination.tpl)
import(components/notifications.tpl, [data-v-component-notifications])
