DROP TABLE IF EXISTS tax_type;


-- DROP SEQUENCE IF EXISTS tax_type_tax_type_id_seq;
-- CREATE SEQUENCE tax_type_tax_type_id_seq;


CREATE TABLE tax_type (
  "tax_type_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "name" varchar(32) NOT NULL,
  "content" varchar(191) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT now(),
  "updated_at" timestamp(0) NOT NULL DEFAULT now()
  -- PRIMARY KEY("tax_type_id")
);

SELECT setval('tax_type_tax_type_id_seq', 3, true); -- last inserted id by sample data