DROP TABLE IF EXISTS menu;

-- DROP SEQUENCE IF EXISTS menu_seq;
-- CREATE SEQUENCE menu_seq;


CREATE TABLE menu (
  "menu_id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- SERIAL PRIMARY KEY
  "name" varchar(191) NOT NULL DEFAULT '',
  "slug" varchar(191) NOT NULL DEFAULT ''
  -- PRIMARY KEY("menu_id")
);

CREATE INDEX "menu_menu_id" ON menu ("menu_id");
SELECT setval('menu_menu_id_seq', 5, true); -- last inserted id by sample data